// Mocks generated by Mockito 5.4.6 from annotations
// in reverieflutter/test/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i13;

import 'package:cloud_firestore/cloud_firestore.dart' as _i20;
import 'package:firebase_auth/firebase_auth.dart' as _i4;
import 'package:firebase_auth_platform_interface/firebase_auth_platform_interface.dart'
    as _i3;
import 'package:firebase_core/firebase_core.dart' as _i2;
import 'package:flutter_riverpod/flutter_riverpod.dart' as _i19;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i14;
import 'package:reverieflutter/data/model/diary.dart' as _i6;
import 'package:reverieflutter/data/model/diary_cover.dart' as _i7;
import 'package:reverieflutter/data/model/diary_image.dart' as _i10;
import 'package:reverieflutter/data/model/diary_page.dart' as _i8;
import 'package:reverieflutter/data/model/diary_sub_page.dart' as _i9;
import 'package:reverieflutter/data/model/time_capsule.dart' as _i11;
import 'package:reverieflutter/data/model/user.dart' as _i5;
import 'package:reverieflutter/data/repository/diary_repository.dart' as _i16;
import 'package:reverieflutter/data/repository/time_capsule_repository.dart'
    as _i17;
import 'package:reverieflutter/data/repository/user_repository.dart' as _i15;
import 'package:reverieflutter/l10n/app_localizations.dart' as _i18;
import 'package:reverieflutter/notifier/create_time_capsule_notifier.dart'
    as _i12;
import 'package:state_notifier/state_notifier.dart' as _i21;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFirebaseApp_0 extends _i1.SmartFake implements _i2.FirebaseApp {
  _FakeFirebaseApp_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeActionCodeInfo_1 extends _i1.SmartFake
    implements _i3.ActionCodeInfo {
  _FakeActionCodeInfo_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserCredential_2 extends _i1.SmartFake
    implements _i4.UserCredential {
  _FakeUserCredential_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeConfirmationResult_3 extends _i1.SmartFake
    implements _i4.ConfirmationResult {
  _FakeConfirmationResult_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUser_4 extends _i1.SmartFake implements _i5.User {
  _FakeUser_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDiary_5 extends _i1.SmartFake implements _i6.Diary {
  _FakeDiary_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDiaryCover_6 extends _i1.SmartFake implements _i7.DiaryCover {
  _FakeDiaryCover_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDiaryPage_7 extends _i1.SmartFake implements _i8.DiaryPage {
  _FakeDiaryPage_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDiarySubPage_8 extends _i1.SmartFake implements _i9.DiarySubPage {
  _FakeDiarySubPage_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDiaryImage_9 extends _i1.SmartFake implements _i10.DiaryImage {
  _FakeDiaryImage_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTimeCapsule_10 extends _i1.SmartFake implements _i11.TimeCapsule {
  _FakeTimeCapsule_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserMetadata_11 extends _i1.SmartFake implements _i3.UserMetadata {
  _FakeUserMetadata_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMultiFactor_12 extends _i1.SmartFake implements _i4.MultiFactor {
  _FakeMultiFactor_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIdTokenResult_13 extends _i1.SmartFake implements _i3.IdTokenResult {
  _FakeIdTokenResult_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUser_14 extends _i1.SmartFake implements _i4.User {
  _FakeUser_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCreateTimeCapsuleState_15 extends _i1.SmartFake
    implements _i12.CreateTimeCapsuleState {
  _FakeCreateTimeCapsuleState_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [FirebaseAuth].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseAuth extends _i1.Mock implements _i4.FirebaseAuth {
  MockFirebaseAuth() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FirebaseApp get app =>
      (super.noSuchMethod(
            Invocation.getter(#app),
            returnValue: _FakeFirebaseApp_0(this, Invocation.getter(#app)),
          )
          as _i2.FirebaseApp);

  @override
  set app(_i2.FirebaseApp? _app) => super.noSuchMethod(
    Invocation.setter(#app, _app),
    returnValueForMissingStub: null,
  );

  @override
  set tenantId(String? tenantId) => super.noSuchMethod(
    Invocation.setter(#tenantId, tenantId),
    returnValueForMissingStub: null,
  );

  @override
  set customAuthDomain(String? customAuthDomain) => super.noSuchMethod(
    Invocation.setter(#customAuthDomain, customAuthDomain),
    returnValueForMissingStub: null,
  );

  @override
  Map<dynamic, dynamic> get pluginConstants =>
      (super.noSuchMethod(
            Invocation.getter(#pluginConstants),
            returnValue: <dynamic, dynamic>{},
          )
          as Map<dynamic, dynamic>);

  @override
  _i13.Future<void> useAuthEmulator(
    String? host,
    int? port, {
    bool? automaticHostMapping = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #useAuthEmulator,
              [host, port],
              {#automaticHostMapping: automaticHostMapping},
            ),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> applyActionCode(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#applyActionCode, [code]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<_i3.ActionCodeInfo> checkActionCode(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#checkActionCode, [code]),
            returnValue: _i13.Future<_i3.ActionCodeInfo>.value(
              _FakeActionCodeInfo_1(
                this,
                Invocation.method(#checkActionCode, [code]),
              ),
            ),
          )
          as _i13.Future<_i3.ActionCodeInfo>);

  @override
  _i13.Future<void> confirmPasswordReset({
    required String? code,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#confirmPasswordReset, [], {
              #code: code,
              #newPassword: newPassword,
            }),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<_i4.UserCredential> createUserWithEmailAndPassword({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createUserWithEmailAndPassword, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i13.Future<_i4.UserCredential>.value(
              _FakeUserCredential_2(
                this,
                Invocation.method(#createUserWithEmailAndPassword, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i13.Future<_i4.UserCredential>);

  @override
  _i13.Future<List<String>> fetchSignInMethodsForEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#fetchSignInMethodsForEmail, [email]),
            returnValue: _i13.Future<List<String>>.value(<String>[]),
          )
          as _i13.Future<List<String>>);

  @override
  _i13.Future<_i4.UserCredential> getRedirectResult() =>
      (super.noSuchMethod(
            Invocation.method(#getRedirectResult, []),
            returnValue: _i13.Future<_i4.UserCredential>.value(
              _FakeUserCredential_2(
                this,
                Invocation.method(#getRedirectResult, []),
              ),
            ),
          )
          as _i13.Future<_i4.UserCredential>);

  @override
  bool isSignInWithEmailLink(String? emailLink) =>
      (super.noSuchMethod(
            Invocation.method(#isSignInWithEmailLink, [emailLink]),
            returnValue: false,
          )
          as bool);

  @override
  _i13.Stream<_i4.User?> authStateChanges() =>
      (super.noSuchMethod(
            Invocation.method(#authStateChanges, []),
            returnValue: _i13.Stream<_i4.User?>.empty(),
          )
          as _i13.Stream<_i4.User?>);

  @override
  _i13.Stream<_i4.User?> idTokenChanges() =>
      (super.noSuchMethod(
            Invocation.method(#idTokenChanges, []),
            returnValue: _i13.Stream<_i4.User?>.empty(),
          )
          as _i13.Stream<_i4.User?>);

  @override
  _i13.Stream<_i4.User?> userChanges() =>
      (super.noSuchMethod(
            Invocation.method(#userChanges, []),
            returnValue: _i13.Stream<_i4.User?>.empty(),
          )
          as _i13.Stream<_i4.User?>);

  @override
  _i13.Future<void> sendPasswordResetEmail({
    required String? email,
    _i3.ActionCodeSettings? actionCodeSettings,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendPasswordResetEmail, [], {
              #email: email,
              #actionCodeSettings: actionCodeSettings,
            }),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> sendSignInLinkToEmail({
    required String? email,
    required _i3.ActionCodeSettings? actionCodeSettings,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendSignInLinkToEmail, [], {
              #email: email,
              #actionCodeSettings: actionCodeSettings,
            }),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> setLanguageCode(String? languageCode) =>
      (super.noSuchMethod(
            Invocation.method(#setLanguageCode, [languageCode]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> setSettings({
    bool? appVerificationDisabledForTesting = false,
    String? userAccessGroup,
    String? phoneNumber,
    String? smsCode,
    bool? forceRecaptchaFlow,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setSettings, [], {
              #appVerificationDisabledForTesting:
                  appVerificationDisabledForTesting,
              #userAccessGroup: userAccessGroup,
              #phoneNumber: phoneNumber,
              #smsCode: smsCode,
              #forceRecaptchaFlow: forceRecaptchaFlow,
            }),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> setPersistence(_i3.Persistence? persistence) =>
      (super.noSuchMethod(
            Invocation.method(#setPersistence, [persistence]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<_i4.UserCredential> signInAnonymously() =>
      (super.noSuchMethod(
            Invocation.method(#signInAnonymously, []),
            returnValue: _i13.Future<_i4.UserCredential>.value(
              _FakeUserCredential_2(
                this,
                Invocation.method(#signInAnonymously, []),
              ),
            ),
          )
          as _i13.Future<_i4.UserCredential>);

  @override
  _i13.Future<_i4.UserCredential> signInWithCredential(
    _i3.AuthCredential? credential,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithCredential, [credential]),
            returnValue: _i13.Future<_i4.UserCredential>.value(
              _FakeUserCredential_2(
                this,
                Invocation.method(#signInWithCredential, [credential]),
              ),
            ),
          )
          as _i13.Future<_i4.UserCredential>);

  @override
  _i13.Future<_i4.UserCredential> signInWithCustomToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithCustomToken, [token]),
            returnValue: _i13.Future<_i4.UserCredential>.value(
              _FakeUserCredential_2(
                this,
                Invocation.method(#signInWithCustomToken, [token]),
              ),
            ),
          )
          as _i13.Future<_i4.UserCredential>);

  @override
  _i13.Future<_i4.UserCredential> signInWithEmailAndPassword({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmailAndPassword, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i13.Future<_i4.UserCredential>.value(
              _FakeUserCredential_2(
                this,
                Invocation.method(#signInWithEmailAndPassword, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i13.Future<_i4.UserCredential>);

  @override
  _i13.Future<_i4.UserCredential> signInWithEmailLink({
    required String? email,
    required String? emailLink,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmailLink, [], {
              #email: email,
              #emailLink: emailLink,
            }),
            returnValue: _i13.Future<_i4.UserCredential>.value(
              _FakeUserCredential_2(
                this,
                Invocation.method(#signInWithEmailLink, [], {
                  #email: email,
                  #emailLink: emailLink,
                }),
              ),
            ),
          )
          as _i13.Future<_i4.UserCredential>);

  @override
  _i13.Future<_i4.UserCredential> signInWithProvider(
    _i3.AuthProvider? provider,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithProvider, [provider]),
            returnValue: _i13.Future<_i4.UserCredential>.value(
              _FakeUserCredential_2(
                this,
                Invocation.method(#signInWithProvider, [provider]),
              ),
            ),
          )
          as _i13.Future<_i4.UserCredential>);

  @override
  _i13.Future<_i4.ConfirmationResult> signInWithPhoneNumber(
    String? phoneNumber, [
    _i4.RecaptchaVerifier? verifier,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithPhoneNumber, [phoneNumber, verifier]),
            returnValue: _i13.Future<_i4.ConfirmationResult>.value(
              _FakeConfirmationResult_3(
                this,
                Invocation.method(#signInWithPhoneNumber, [
                  phoneNumber,
                  verifier,
                ]),
              ),
            ),
          )
          as _i13.Future<_i4.ConfirmationResult>);

  @override
  _i13.Future<_i4.UserCredential> signInWithPopup(_i3.AuthProvider? provider) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithPopup, [provider]),
            returnValue: _i13.Future<_i4.UserCredential>.value(
              _FakeUserCredential_2(
                this,
                Invocation.method(#signInWithPopup, [provider]),
              ),
            ),
          )
          as _i13.Future<_i4.UserCredential>);

  @override
  _i13.Future<void> signInWithRedirect(_i3.AuthProvider? provider) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithRedirect, [provider]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<String> verifyPasswordResetCode(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#verifyPasswordResetCode, [code]),
            returnValue: _i13.Future<String>.value(
              _i14.dummyValue<String>(
                this,
                Invocation.method(#verifyPasswordResetCode, [code]),
              ),
            ),
          )
          as _i13.Future<String>);

  @override
  _i13.Future<void> verifyPhoneNumber({
    String? phoneNumber,
    _i3.PhoneMultiFactorInfo? multiFactorInfo,
    required _i3.PhoneVerificationCompleted? verificationCompleted,
    required _i3.PhoneVerificationFailed? verificationFailed,
    required _i3.PhoneCodeSent? codeSent,
    required _i3.PhoneCodeAutoRetrievalTimeout? codeAutoRetrievalTimeout,
    String? autoRetrievedSmsCodeForTesting,
    Duration? timeout = const Duration(seconds: 30),
    int? forceResendingToken,
    _i3.MultiFactorSession? multiFactorSession,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyPhoneNumber, [], {
              #phoneNumber: phoneNumber,
              #multiFactorInfo: multiFactorInfo,
              #verificationCompleted: verificationCompleted,
              #verificationFailed: verificationFailed,
              #codeSent: codeSent,
              #codeAutoRetrievalTimeout: codeAutoRetrievalTimeout,
              #autoRetrievedSmsCodeForTesting: autoRetrievedSmsCodeForTesting,
              #timeout: timeout,
              #forceResendingToken: forceResendingToken,
              #multiFactorSession: multiFactorSession,
            }),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> revokeTokenWithAuthorizationCode(
    String? authorizationCode,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#revokeTokenWithAuthorizationCode, [
              authorizationCode,
            ]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> initializeRecaptchaConfig() =>
      (super.noSuchMethod(
            Invocation.method(#initializeRecaptchaConfig, []),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i15.UserRepository {
  MockUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i5.User> getUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUser, [userId]),
            returnValue: _i13.Future<_i5.User>.value(
              _FakeUser_4(this, Invocation.method(#getUser, [userId])),
            ),
          )
          as _i13.Future<_i5.User>);

  @override
  _i13.Future<bool> isUsernameTaken(String? username) =>
      (super.noSuchMethod(
            Invocation.method(#isUsernameTaken, [username]),
            returnValue: _i13.Future<bool>.value(false),
          )
          as _i13.Future<bool>);

  @override
  _i13.Future<bool> isEmailTaken(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#isEmailTaken, [email]),
            returnValue: _i13.Future<bool>.value(false),
          )
          as _i13.Future<bool>);

  @override
  _i13.Future<void> updateUser(_i5.User? user) =>
      (super.noSuchMethod(
            Invocation.method(#updateUser, [user]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<bool> authenticate(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#authenticate, [email, password]),
            returnValue: _i13.Future<bool>.value(false),
          )
          as _i13.Future<bool>);

  @override
  _i13.Future<_i5.User?> createAccount(_i5.User? user, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#createAccount, [user, password]),
            returnValue: _i13.Future<_i5.User?>.value(),
          )
          as _i13.Future<_i5.User?>);

  @override
  Null sendPasswordResetEmail(String? email) =>
      (super.noSuchMethod(Invocation.method(#sendPasswordResetEmail, [email]))
          as Null);

  @override
  _i13.Future<List<_i5.User>> getUsersMatchingPartialUsername(
    String? partialUsername,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUsersMatchingPartialUsername, [
              partialUsername,
            ]),
            returnValue: _i13.Future<List<_i5.User>>.value(<_i5.User>[]),
          )
          as _i13.Future<List<_i5.User>>);
}

/// A class which mocks [DiaryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDiaryRepository extends _i1.Mock implements _i16.DiaryRepository {
  MockDiaryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i6.Diary> getDiary(String? diaryId) =>
      (super.noSuchMethod(
            Invocation.method(#getDiary, [diaryId]),
            returnValue: _i13.Future<_i6.Diary>.value(
              _FakeDiary_5(this, Invocation.method(#getDiary, [diaryId])),
            ),
          )
          as _i13.Future<_i6.Diary>);

  @override
  _i13.Future<List<_i6.Diary>> getUserDiaries(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserDiaries, [userId]),
            returnValue: _i13.Future<List<_i6.Diary>>.value(<_i6.Diary>[]),
          )
          as _i13.Future<List<_i6.Diary>>);

  @override
  _i13.Future<_i6.Diary> saveDiary(_i6.Diary? diary) =>
      (super.noSuchMethod(
            Invocation.method(#saveDiary, [diary]),
            returnValue: _i13.Future<_i6.Diary>.value(
              _FakeDiary_5(this, Invocation.method(#saveDiary, [diary])),
            ),
          )
          as _i13.Future<_i6.Diary>);

  @override
  _i13.Future<void> updateDiary(_i6.Diary? diary) =>
      (super.noSuchMethod(
            Invocation.method(#updateDiary, [diary]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> deleteDiary(_i6.Diary? diary) =>
      (super.noSuchMethod(
            Invocation.method(#deleteDiary, [diary]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<_i7.DiaryCover> getDiaryCover(String? diaryCoverId) =>
      (super.noSuchMethod(
            Invocation.method(#getDiaryCover, [diaryCoverId]),
            returnValue: _i13.Future<_i7.DiaryCover>.value(
              _FakeDiaryCover_6(
                this,
                Invocation.method(#getDiaryCover, [diaryCoverId]),
              ),
            ),
          )
          as _i13.Future<_i7.DiaryCover>);

  @override
  _i13.Future<_i8.DiaryPage> getPage(String? pageId) =>
      (super.noSuchMethod(
            Invocation.method(#getPage, [pageId]),
            returnValue: _i13.Future<_i8.DiaryPage>.value(
              _FakeDiaryPage_7(this, Invocation.method(#getPage, [pageId])),
            ),
          )
          as _i13.Future<_i8.DiaryPage>);

  @override
  _i13.Future<_i8.DiaryPage> savePage(_i8.DiaryPage? page) =>
      (super.noSuchMethod(
            Invocation.method(#savePage, [page]),
            returnValue: _i13.Future<_i8.DiaryPage>.value(
              _FakeDiaryPage_7(this, Invocation.method(#savePage, [page])),
            ),
          )
          as _i13.Future<_i8.DiaryPage>);

  @override
  _i13.Future<void> updatePage(_i8.DiaryPage? page) =>
      (super.noSuchMethod(
            Invocation.method(#updatePage, [page]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> deletePage(_i8.DiaryPage? page) =>
      (super.noSuchMethod(
            Invocation.method(#deletePage, [page]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<_i9.DiarySubPage> getSubPage(String? subPageId) =>
      (super.noSuchMethod(
            Invocation.method(#getSubPage, [subPageId]),
            returnValue: _i13.Future<_i9.DiarySubPage>.value(
              _FakeDiarySubPage_8(
                this,
                Invocation.method(#getSubPage, [subPageId]),
              ),
            ),
          )
          as _i13.Future<_i9.DiarySubPage>);

  @override
  _i13.Future<_i9.DiarySubPage> saveSubPage(_i9.DiarySubPage? subPage) =>
      (super.noSuchMethod(
            Invocation.method(#saveSubPage, [subPage]),
            returnValue: _i13.Future<_i9.DiarySubPage>.value(
              _FakeDiarySubPage_8(
                this,
                Invocation.method(#saveSubPage, [subPage]),
              ),
            ),
          )
          as _i13.Future<_i9.DiarySubPage>);

  @override
  _i13.Future<void> updateSubPage(_i9.DiarySubPage? subPage) =>
      (super.noSuchMethod(
            Invocation.method(#updateSubPage, [subPage]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> deleteSubPage(_i9.DiarySubPage? subPage) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSubPage, [subPage]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<_i10.DiaryImage> getDiaryImage(String? diaryImageId) =>
      (super.noSuchMethod(
            Invocation.method(#getDiaryImage, [diaryImageId]),
            returnValue: _i13.Future<_i10.DiaryImage>.value(
              _FakeDiaryImage_9(
                this,
                Invocation.method(#getDiaryImage, [diaryImageId]),
              ),
            ),
          )
          as _i13.Future<_i10.DiaryImage>);

  @override
  _i13.Future<void> deleteDiaryImage(_i10.DiaryImage? diaryImage) =>
      (super.noSuchMethod(
            Invocation.method(#deleteDiaryImage, [diaryImage]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<List<_i7.DiaryCover>> getAllDiaryCovers() =>
      (super.noSuchMethod(
            Invocation.method(#getAllDiaryCovers, []),
            returnValue: _i13.Future<List<_i7.DiaryCover>>.value(
              <_i7.DiaryCover>[],
            ),
          )
          as _i13.Future<List<_i7.DiaryCover>>);
}

/// A class which mocks [TimeCapsuleRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTimeCapsuleRepository extends _i1.Mock
    implements _i17.TimeCapsuleRepository {
  MockTimeCapsuleRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<List<_i11.TimeCapsule>> getUserSentTimeCapsules(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserSentTimeCapsules, [userId]),
            returnValue: _i13.Future<List<_i11.TimeCapsule>>.value(
              <_i11.TimeCapsule>[],
            ),
          )
          as _i13.Future<List<_i11.TimeCapsule>>);

  @override
  _i13.Future<List<_i11.TimeCapsule>> getUserReceivedTimeCapsules(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUserReceivedTimeCapsules, [userId]),
            returnValue: _i13.Future<List<_i11.TimeCapsule>>.value(
              <_i11.TimeCapsule>[],
            ),
          )
          as _i13.Future<List<_i11.TimeCapsule>>);

  @override
  _i13.Future<_i11.TimeCapsule> getTimeCapsule(String? timeCapsuleId) =>
      (super.noSuchMethod(
            Invocation.method(#getTimeCapsule, [timeCapsuleId]),
            returnValue: _i13.Future<_i11.TimeCapsule>.value(
              _FakeTimeCapsule_10(
                this,
                Invocation.method(#getTimeCapsule, [timeCapsuleId]),
              ),
            ),
          )
          as _i13.Future<_i11.TimeCapsule>);

  @override
  _i13.Future<_i11.TimeCapsule> saveTimeCapsule(
    _i11.TimeCapsule? timeCapsule,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveTimeCapsule, [timeCapsule]),
            returnValue: _i13.Future<_i11.TimeCapsule>.value(
              _FakeTimeCapsule_10(
                this,
                Invocation.method(#saveTimeCapsule, [timeCapsule]),
              ),
            ),
          )
          as _i13.Future<_i11.TimeCapsule>);

  @override
  _i13.Future<void> deleteTimeCapsule(_i11.TimeCapsule? timeCapsule) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTimeCapsule, [timeCapsule]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);
}

/// A class which mocks [User].
///
/// See the documentation for Mockito's code generation for more information.
class MockUser extends _i1.Mock implements _i4.User {
  MockUser() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get emailVerified =>
      (super.noSuchMethod(Invocation.getter(#emailVerified), returnValue: false)
          as bool);

  @override
  bool get isAnonymous =>
      (super.noSuchMethod(Invocation.getter(#isAnonymous), returnValue: false)
          as bool);

  @override
  _i3.UserMetadata get metadata =>
      (super.noSuchMethod(
            Invocation.getter(#metadata),
            returnValue: _FakeUserMetadata_11(
              this,
              Invocation.getter(#metadata),
            ),
          )
          as _i3.UserMetadata);

  @override
  List<_i3.UserInfo> get providerData =>
      (super.noSuchMethod(
            Invocation.getter(#providerData),
            returnValue: <_i3.UserInfo>[],
          )
          as List<_i3.UserInfo>);

  @override
  String get uid =>
      (super.noSuchMethod(
            Invocation.getter(#uid),
            returnValue: _i14.dummyValue<String>(this, Invocation.getter(#uid)),
          )
          as String);

  @override
  _i4.MultiFactor get multiFactor =>
      (super.noSuchMethod(
            Invocation.getter(#multiFactor),
            returnValue: _FakeMultiFactor_12(
              this,
              Invocation.getter(#multiFactor),
            ),
          )
          as _i4.MultiFactor);

  @override
  _i13.Future<void> delete() =>
      (super.noSuchMethod(
            Invocation.method(#delete, []),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<String?> getIdToken([bool? forceRefresh = false]) =>
      (super.noSuchMethod(
            Invocation.method(#getIdToken, [forceRefresh]),
            returnValue: _i13.Future<String?>.value(),
          )
          as _i13.Future<String?>);

  @override
  _i13.Future<_i3.IdTokenResult> getIdTokenResult([
    bool? forceRefresh = false,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#getIdTokenResult, [forceRefresh]),
            returnValue: _i13.Future<_i3.IdTokenResult>.value(
              _FakeIdTokenResult_13(
                this,
                Invocation.method(#getIdTokenResult, [forceRefresh]),
              ),
            ),
          )
          as _i13.Future<_i3.IdTokenResult>);

  @override
  _i13.Future<_i4.UserCredential> linkWithCredential(
    _i3.AuthCredential? credential,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#linkWithCredential, [credential]),
            returnValue: _i13.Future<_i4.UserCredential>.value(
              _FakeUserCredential_2(
                this,
                Invocation.method(#linkWithCredential, [credential]),
              ),
            ),
          )
          as _i13.Future<_i4.UserCredential>);

  @override
  _i13.Future<_i4.UserCredential> linkWithProvider(
    _i3.AuthProvider? provider,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#linkWithProvider, [provider]),
            returnValue: _i13.Future<_i4.UserCredential>.value(
              _FakeUserCredential_2(
                this,
                Invocation.method(#linkWithProvider, [provider]),
              ),
            ),
          )
          as _i13.Future<_i4.UserCredential>);

  @override
  _i13.Future<_i4.UserCredential> reauthenticateWithProvider(
    _i3.AuthProvider? provider,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#reauthenticateWithProvider, [provider]),
            returnValue: _i13.Future<_i4.UserCredential>.value(
              _FakeUserCredential_2(
                this,
                Invocation.method(#reauthenticateWithProvider, [provider]),
              ),
            ),
          )
          as _i13.Future<_i4.UserCredential>);

  @override
  _i13.Future<_i4.UserCredential> reauthenticateWithPopup(
    _i3.AuthProvider? provider,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#reauthenticateWithPopup, [provider]),
            returnValue: _i13.Future<_i4.UserCredential>.value(
              _FakeUserCredential_2(
                this,
                Invocation.method(#reauthenticateWithPopup, [provider]),
              ),
            ),
          )
          as _i13.Future<_i4.UserCredential>);

  @override
  _i13.Future<void> reauthenticateWithRedirect(_i3.AuthProvider? provider) =>
      (super.noSuchMethod(
            Invocation.method(#reauthenticateWithRedirect, [provider]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<_i4.UserCredential> linkWithPopup(_i3.AuthProvider? provider) =>
      (super.noSuchMethod(
            Invocation.method(#linkWithPopup, [provider]),
            returnValue: _i13.Future<_i4.UserCredential>.value(
              _FakeUserCredential_2(
                this,
                Invocation.method(#linkWithPopup, [provider]),
              ),
            ),
          )
          as _i13.Future<_i4.UserCredential>);

  @override
  _i13.Future<void> linkWithRedirect(_i3.AuthProvider? provider) =>
      (super.noSuchMethod(
            Invocation.method(#linkWithRedirect, [provider]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<_i4.ConfirmationResult> linkWithPhoneNumber(
    String? phoneNumber, [
    _i4.RecaptchaVerifier? verifier,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#linkWithPhoneNumber, [phoneNumber, verifier]),
            returnValue: _i13.Future<_i4.ConfirmationResult>.value(
              _FakeConfirmationResult_3(
                this,
                Invocation.method(#linkWithPhoneNumber, [
                  phoneNumber,
                  verifier,
                ]),
              ),
            ),
          )
          as _i13.Future<_i4.ConfirmationResult>);

  @override
  _i13.Future<_i4.UserCredential> reauthenticateWithCredential(
    _i3.AuthCredential? credential,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#reauthenticateWithCredential, [credential]),
            returnValue: _i13.Future<_i4.UserCredential>.value(
              _FakeUserCredential_2(
                this,
                Invocation.method(#reauthenticateWithCredential, [credential]),
              ),
            ),
          )
          as _i13.Future<_i4.UserCredential>);

  @override
  _i13.Future<void> reload() =>
      (super.noSuchMethod(
            Invocation.method(#reload, []),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> sendEmailVerification([
    _i3.ActionCodeSettings? actionCodeSettings,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#sendEmailVerification, [actionCodeSettings]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<_i4.User> unlink(String? providerId) =>
      (super.noSuchMethod(
            Invocation.method(#unlink, [providerId]),
            returnValue: _i13.Future<_i4.User>.value(
              _FakeUser_14(this, Invocation.method(#unlink, [providerId])),
            ),
          )
          as _i13.Future<_i4.User>);

  @override
  _i13.Future<void> updateEmail(String? newEmail) =>
      (super.noSuchMethod(
            Invocation.method(#updateEmail, [newEmail]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> updatePassword(String? newPassword) =>
      (super.noSuchMethod(
            Invocation.method(#updatePassword, [newPassword]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> updatePhoneNumber(
    _i3.PhoneAuthCredential? phoneCredential,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updatePhoneNumber, [phoneCredential]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> updateDisplayName(String? displayName) =>
      (super.noSuchMethod(
            Invocation.method(#updateDisplayName, [displayName]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> updatePhotoURL(String? photoURL) =>
      (super.noSuchMethod(
            Invocation.method(#updatePhotoURL, [photoURL]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> updateProfile({String? displayName, String? photoURL}) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [], {
              #displayName: displayName,
              #photoURL: photoURL,
            }),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> verifyBeforeUpdateEmail(
    String? newEmail, [
    _i3.ActionCodeSettings? actionCodeSettings,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#verifyBeforeUpdateEmail, [
              newEmail,
              actionCodeSettings,
            ]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);
}

/// A class which mocks [AppLocalizations].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppLocalizations extends _i1.Mock implements _i18.AppLocalizations {
  MockAppLocalizations() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get localeName =>
      (super.noSuchMethod(
            Invocation.getter(#localeName),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#localeName),
            ),
          )
          as String);

  @override
  String get appName =>
      (super.noSuchMethod(
            Invocation.getter(#appName),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#appName),
            ),
          )
          as String);

  @override
  String get allDiaries =>
      (super.noSuchMethod(
            Invocation.getter(#allDiaries),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#allDiaries),
            ),
          )
          as String);

  @override
  String get diary =>
      (super.noSuchMethod(
            Invocation.getter(#diary),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#diary),
            ),
          )
          as String);

  @override
  String get timeCapsule =>
      (super.noSuchMethod(
            Invocation.getter(#timeCapsule),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#timeCapsule),
            ),
          )
          as String);

  @override
  String get navigationDrawer =>
      (super.noSuchMethod(
            Invocation.getter(#navigationDrawer),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#navigationDrawer),
            ),
          )
          as String);

  @override
  String get account =>
      (super.noSuchMethod(
            Invocation.getter(#account),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#account),
            ),
          )
          as String);

  @override
  String get email =>
      (super.noSuchMethod(
            Invocation.getter(#email),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#email),
            ),
          )
          as String);

  @override
  String get username =>
      (super.noSuchMethod(
            Invocation.getter(#username),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#username),
            ),
          )
          as String);

  @override
  String get password =>
      (super.noSuchMethod(
            Invocation.getter(#password),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#password),
            ),
          )
          as String);

  @override
  String get confirmPassword =>
      (super.noSuchMethod(
            Invocation.getter(#confirmPassword),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#confirmPassword),
            ),
          )
          as String);

  @override
  String get login =>
      (super.noSuchMethod(
            Invocation.getter(#login),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#login),
            ),
          )
          as String);

  @override
  String get logout =>
      (super.noSuchMethod(
            Invocation.getter(#logout),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#logout),
            ),
          )
          as String);

  @override
  String get signup =>
      (super.noSuchMethod(
            Invocation.getter(#signup),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#signup),
            ),
          )
          as String);

  @override
  String get title =>
      (super.noSuchMethod(
            Invocation.getter(#title),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#title),
            ),
          )
          as String);

  @override
  String get description =>
      (super.noSuchMethod(
            Invocation.getter(#description),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#description),
            ),
          )
          as String);

  @override
  String get page =>
      (super.noSuchMethod(
            Invocation.getter(#page),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#page),
            ),
          )
          as String);

  @override
  String get subPage =>
      (super.noSuchMethod(
            Invocation.getter(#subPage),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#subPage),
            ),
          )
          as String);

  @override
  String get day =>
      (super.noSuchMethod(
            Invocation.getter(#day),
            returnValue: _i14.dummyValue<String>(this, Invocation.getter(#day)),
          )
          as String);

  @override
  String get delete =>
      (super.noSuchMethod(
            Invocation.getter(#delete),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#delete),
            ),
          )
          as String);

  @override
  String get cancel =>
      (super.noSuchMethod(
            Invocation.getter(#cancel),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#cancel),
            ),
          )
          as String);

  @override
  String get moveUp =>
      (super.noSuchMethod(
            Invocation.getter(#moveUp),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#moveUp),
            ),
          )
          as String);

  @override
  String get moveDown =>
      (super.noSuchMethod(
            Invocation.getter(#moveDown),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#moveDown),
            ),
          )
          as String);

  @override
  String get newDiary =>
      (super.noSuchMethod(
            Invocation.getter(#newDiary),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#newDiary),
            ),
          )
          as String);

  @override
  String get create =>
      (super.noSuchMethod(
            Invocation.getter(#create),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#create),
            ),
          )
          as String);

  @override
  String get save =>
      (super.noSuchMethod(
            Invocation.getter(#save),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#save),
            ),
          )
          as String);

  @override
  String get createDiaryMessage =>
      (super.noSuchMethod(
            Invocation.getter(#createDiaryMessage),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#createDiaryMessage),
            ),
          )
          as String);

  @override
  String get editDiaryPageMessage =>
      (super.noSuchMethod(
            Invocation.getter(#editDiaryPageMessage),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#editDiaryPageMessage),
            ),
          )
          as String);

  @override
  String get createDiary =>
      (super.noSuchMethod(
            Invocation.getter(#createDiary),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#createDiary),
            ),
          )
          as String);

  @override
  String get editDiaryMessage =>
      (super.noSuchMethod(
            Invocation.getter(#editDiaryMessage),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#editDiaryMessage),
            ),
          )
          as String);

  @override
  String get createTimeCapsuleMessage =>
      (super.noSuchMethod(
            Invocation.getter(#createTimeCapsuleMessage),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#createTimeCapsuleMessage),
            ),
          )
          as String);

  @override
  String get content =>
      (super.noSuchMethod(
            Invocation.getter(#content),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#content),
            ),
          )
          as String);

  @override
  String get yourProfile =>
      (super.noSuchMethod(
            Invocation.getter(#yourProfile),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#yourProfile),
            ),
          )
          as String);

  @override
  String get name =>
      (super.noSuchMethod(
            Invocation.getter(#name),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#name),
            ),
          )
          as String);

  @override
  String get surname =>
      (super.noSuchMethod(
            Invocation.getter(#surname),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#surname),
            ),
          )
          as String);

  @override
  String get editProfile =>
      (super.noSuchMethod(
            Invocation.getter(#editProfile),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#editProfile),
            ),
          )
          as String);

  @override
  String get emailMandatory =>
      (super.noSuchMethod(
            Invocation.getter(#emailMandatory),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#emailMandatory),
            ),
          )
          as String);

  @override
  String get usernameMandatory =>
      (super.noSuchMethod(
            Invocation.getter(#usernameMandatory),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#usernameMandatory),
            ),
          )
          as String);

  @override
  String get nameMandatory =>
      (super.noSuchMethod(
            Invocation.getter(#nameMandatory),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#nameMandatory),
            ),
          )
          as String);

  @override
  String get surnameMandatory =>
      (super.noSuchMethod(
            Invocation.getter(#surnameMandatory),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#surnameMandatory),
            ),
          )
          as String);

  @override
  String get titleMandatory =>
      (super.noSuchMethod(
            Invocation.getter(#titleMandatory),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#titleMandatory),
            ),
          )
          as String);

  @override
  String get descriptionMandatory =>
      (super.noSuchMethod(
            Invocation.getter(#descriptionMandatory),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#descriptionMandatory),
            ),
          )
          as String);

  @override
  String get contentMandatory =>
      (super.noSuchMethod(
            Invocation.getter(#contentMandatory),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#contentMandatory),
            ),
          )
          as String);

  @override
  String get passwordMandatory =>
      (super.noSuchMethod(
            Invocation.getter(#passwordMandatory),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#passwordMandatory),
            ),
          )
          as String);

  @override
  String get passwordsDontMatch =>
      (super.noSuchMethod(
            Invocation.getter(#passwordsDontMatch),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#passwordsDontMatch),
            ),
          )
          as String);

  @override
  String get passwordLength =>
      (super.noSuchMethod(
            Invocation.getter(#passwordLength),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#passwordLength),
            ),
          )
          as String);

  @override
  String get usernameLength =>
      (super.noSuchMethod(
            Invocation.getter(#usernameLength),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#usernameLength),
            ),
          )
          as String);

  @override
  String get sendResetPasswordEmail =>
      (super.noSuchMethod(
            Invocation.getter(#sendResetPasswordEmail),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#sendResetPasswordEmail),
            ),
          )
          as String);

  @override
  String get goBackToLogin =>
      (super.noSuchMethod(
            Invocation.getter(#goBackToLogin),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#goBackToLogin),
            ),
          )
          as String);

  @override
  String get resetPassword =>
      (super.noSuchMethod(
            Invocation.getter(#resetPassword),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#resetPassword),
            ),
          )
          as String);

  @override
  String get resetPasswordEmailSent =>
      (super.noSuchMethod(
            Invocation.getter(#resetPasswordEmailSent),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#resetPasswordEmailSent),
            ),
          )
          as String);

  @override
  String get resetPasswordEmailError =>
      (super.noSuchMethod(
            Invocation.getter(#resetPasswordEmailError),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#resetPasswordEmailError),
            ),
          )
          as String);

  @override
  String get goToSignup =>
      (super.noSuchMethod(
            Invocation.getter(#goToSignup),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#goToSignup),
            ),
          )
          as String);

  @override
  String get forgotPassword =>
      (super.noSuchMethod(
            Invocation.getter(#forgotPassword),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#forgotPassword),
            ),
          )
          as String);

  @override
  String get alreadyHaveAccount =>
      (super.noSuchMethod(
            Invocation.getter(#alreadyHaveAccount),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#alreadyHaveAccount),
            ),
          )
          as String);

  @override
  String get signupSuccessful =>
      (super.noSuchMethod(
            Invocation.getter(#signupSuccessful),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#signupSuccessful),
            ),
          )
          as String);

  @override
  String get signupError =>
      (super.noSuchMethod(
            Invocation.getter(#signupError),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#signupError),
            ),
          )
          as String);

  @override
  String get loginError =>
      (super.noSuchMethod(
            Invocation.getter(#loginError),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#loginError),
            ),
          )
          as String);

  @override
  String get noDateSelected =>
      (super.noSuchMethod(
            Invocation.getter(#noDateSelected),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#noDateSelected),
            ),
          )
          as String);

  @override
  String get date =>
      (super.noSuchMethod(
            Invocation.getter(#date),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#date),
            ),
          )
          as String);

  @override
  String get selectDate =>
      (super.noSuchMethod(
            Invocation.getter(#selectDate),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#selectDate),
            ),
          )
          as String);

  @override
  String get error =>
      (super.noSuchMethod(
            Invocation.getter(#error),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#error),
            ),
          )
          as String);

  @override
  String get usernameAlreadyTaken =>
      (super.noSuchMethod(
            Invocation.getter(#usernameAlreadyTaken),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#usernameAlreadyTaken),
            ),
          )
          as String);

  @override
  String get emailAlreadyTaken =>
      (super.noSuchMethod(
            Invocation.getter(#emailAlreadyTaken),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#emailAlreadyTaken),
            ),
          )
          as String);

  @override
  String get selectADate =>
      (super.noSuchMethod(
            Invocation.getter(#selectADate),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#selectADate),
            ),
          )
          as String);

  @override
  String get emailNotValid =>
      (super.noSuchMethod(
            Invocation.getter(#emailNotValid),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#emailNotValid),
            ),
          )
          as String);

  @override
  String get saveChanges =>
      (super.noSuchMethod(
            Invocation.getter(#saveChanges),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#saveChanges),
            ),
          )
          as String);

  @override
  String get updateError =>
      (super.noSuchMethod(
            Invocation.getter(#updateError),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#updateError),
            ),
          )
          as String);

  @override
  String get confirmDiaryDeletion =>
      (super.noSuchMethod(
            Invocation.getter(#confirmDiaryDeletion),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#confirmDiaryDeletion),
            ),
          )
          as String);

  @override
  String get deleteDiary =>
      (super.noSuchMethod(
            Invocation.getter(#deleteDiary),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#deleteDiary),
            ),
          )
          as String);

  @override
  String get confirmPageDeletion =>
      (super.noSuchMethod(
            Invocation.getter(#confirmPageDeletion),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#confirmPageDeletion),
            ),
          )
          as String);

  @override
  String get deletePage =>
      (super.noSuchMethod(
            Invocation.getter(#deletePage),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#deletePage),
            ),
          )
          as String);

  @override
  String get movePrevSubpage =>
      (super.noSuchMethod(
            Invocation.getter(#movePrevSubpage),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#movePrevSubpage),
            ),
          )
          as String);

  @override
  String get moveNextSubpage =>
      (super.noSuchMethod(
            Invocation.getter(#moveNextSubpage),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#moveNextSubpage),
            ),
          )
          as String);

  @override
  String get receiverMandatory =>
      (super.noSuchMethod(
            Invocation.getter(#receiverMandatory),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#receiverMandatory),
            ),
          )
          as String);

  @override
  String get deadlineMandatory =>
      (super.noSuchMethod(
            Invocation.getter(#deadlineMandatory),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#deadlineMandatory),
            ),
          )
          as String);

  @override
  String get missingPhonePrefix =>
      (super.noSuchMethod(
            Invocation.getter(#missingPhonePrefix),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#missingPhonePrefix),
            ),
          )
          as String);

  @override
  String get phoneNumberNotValid =>
      (super.noSuchMethod(
            Invocation.getter(#phoneNumberNotValid),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#phoneNumberNotValid),
            ),
          )
          as String);

  @override
  String get phoneNumber =>
      (super.noSuchMethod(
            Invocation.getter(#phoneNumber),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#phoneNumber),
            ),
          )
          as String);

  @override
  String get phoneNumberAlreadySelected =>
      (super.noSuchMethod(
            Invocation.getter(#phoneNumberAlreadySelected),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#phoneNumberAlreadySelected),
            ),
          )
          as String);

  @override
  String get emailAlreadySelected =>
      (super.noSuchMethod(
            Invocation.getter(#emailAlreadySelected),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#emailAlreadySelected),
            ),
          )
          as String);

  @override
  String get editDiary =>
      (super.noSuchMethod(
            Invocation.getter(#editDiary),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#editDiary),
            ),
          )
          as String);

  @override
  String get selectImage =>
      (super.noSuchMethod(
            Invocation.getter(#selectImage),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#selectImage),
            ),
          )
          as String);

  @override
  String get arrivalDate =>
      (super.noSuchMethod(
            Invocation.getter(#arrivalDate),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#arrivalDate),
            ),
          )
          as String);

  @override
  String get creationDate =>
      (super.noSuchMethod(
            Invocation.getter(#creationDate),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#creationDate),
            ),
          )
          as String);

  @override
  String get receiver =>
      (super.noSuchMethod(
            Invocation.getter(#receiver),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#receiver),
            ),
          )
          as String);

  @override
  String get receivers =>
      (super.noSuchMethod(
            Invocation.getter(#receivers),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#receivers),
            ),
          )
          as String);

  @override
  String get sender =>
      (super.noSuchMethod(
            Invocation.getter(#sender),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#sender),
            ),
          )
          as String);

  @override
  String get contentNotAvailable =>
      (super.noSuchMethod(
            Invocation.getter(#contentNotAvailable),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#contentNotAvailable),
            ),
          )
          as String);

  @override
  String get letterContent =>
      (super.noSuchMethod(
            Invocation.getter(#letterContent),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#letterContent),
            ),
          )
          as String);

  @override
  String get profile =>
      (super.noSuchMethod(
            Invocation.getter(#profile),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#profile),
            ),
          )
          as String);

  @override
  String get pageNumber =>
      (super.noSuchMethod(
            Invocation.getter(#pageNumber),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#pageNumber),
            ),
          )
          as String);

  @override
  String get createTimeCapsule =>
      (super.noSuchMethod(
            Invocation.getter(#createTimeCapsule),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#createTimeCapsule),
            ),
          )
          as String);

  @override
  String get letterForTheFuture =>
      (super.noSuchMethod(
            Invocation.getter(#letterForTheFuture),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#letterForTheFuture),
            ),
          )
          as String);

  @override
  String get letterForTheFutureDescription =>
      (super.noSuchMethod(
            Invocation.getter(#letterForTheFutureDescription),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#letterForTheFutureDescription),
            ),
          )
          as String);

  @override
  String get createdOn =>
      (super.noSuchMethod(
            Invocation.getter(#createdOn),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#createdOn),
            ),
          )
          as String);

  @override
  String get arrivingOn =>
      (super.noSuchMethod(
            Invocation.getter(#arrivingOn),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#arrivingOn),
            ),
          )
          as String);

  @override
  String get arrivedOn =>
      (super.noSuchMethod(
            Invocation.getter(#arrivedOn),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#arrivedOn),
            ),
          )
          as String);

  @override
  String get editDiaryPage =>
      (super.noSuchMethod(
            Invocation.getter(#editDiaryPage),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#editDiaryPage),
            ),
          )
          as String);

  @override
  String get add =>
      (super.noSuchMethod(
            Invocation.getter(#add),
            returnValue: _i14.dummyValue<String>(this, Invocation.getter(#add)),
          )
          as String);

  @override
  String get enterPhoneNumber =>
      (super.noSuchMethod(
            Invocation.getter(#enterPhoneNumber),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#enterPhoneNumber),
            ),
          )
          as String);

  @override
  String get enterEmail =>
      (super.noSuchMethod(
            Invocation.getter(#enterEmail),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#enterEmail),
            ),
          )
          as String);

  @override
  String get errorMessage =>
      (super.noSuchMethod(
            Invocation.getter(#errorMessage),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#errorMessage),
            ),
          )
          as String);

  @override
  String get settings =>
      (super.noSuchMethod(
            Invocation.getter(#settings),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#settings),
            ),
          )
          as String);

  @override
  String get help =>
      (super.noSuchMethod(
            Invocation.getter(#help),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#help),
            ),
          )
          as String);

  @override
  String get reverie =>
      (super.noSuchMethod(
            Invocation.getter(#reverie),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#reverie),
            ),
          )
          as String);

  @override
  String get userNotSignedIn =>
      (super.noSuchMethod(
            Invocation.getter(#userNotSignedIn),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#userNotSignedIn),
            ),
          )
          as String);

  @override
  String get generalInfo =>
      (super.noSuchMethod(
            Invocation.getter(#generalInfo),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#generalInfo),
            ),
          )
          as String);

  @override
  String get scheduled =>
      (super.noSuchMethod(
            Invocation.getter(#scheduled),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#scheduled),
            ),
          )
          as String);

  @override
  String get sent =>
      (super.noSuchMethod(
            Invocation.getter(#sent),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#sent),
            ),
          )
          as String);

  @override
  String get received =>
      (super.noSuchMethod(
            Invocation.getter(#received),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#received),
            ),
          )
          as String);
}

/// A class which mocks [CreateTimeCapsuleNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateTimeCapsuleNotifier extends _i1.Mock
    implements _i12.CreateTimeCapsuleNotifier {
  MockCreateTimeCapsuleNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get mounted =>
      (super.noSuchMethod(Invocation.getter(#mounted), returnValue: false)
          as bool);

  @override
  _i13.Stream<_i12.CreateTimeCapsuleState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i13.Stream<_i12.CreateTimeCapsuleState>.empty(),
          )
          as _i13.Stream<_i12.CreateTimeCapsuleState>);

  @override
  _i12.CreateTimeCapsuleState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeCreateTimeCapsuleState_15(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i12.CreateTimeCapsuleState);

  @override
  _i12.CreateTimeCapsuleState get debugState =>
      (super.noSuchMethod(
            Invocation.getter(#debugState),
            returnValue: _FakeCreateTimeCapsuleState_15(
              this,
              Invocation.getter(#debugState),
            ),
          )
          as _i12.CreateTimeCapsuleState);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  set onError(_i19.ErrorListener? _onError) => super.noSuchMethod(
    Invocation.setter(#onError, _onError),
    returnValueForMissingStub: null,
  );

  @override
  set state(_i12.CreateTimeCapsuleState? value) => super.noSuchMethod(
    Invocation.setter(#state, value),
    returnValueForMissingStub: null,
  );

  @override
  String validateTitle(String? title) =>
      (super.noSuchMethod(
            Invocation.method(#validateTitle, [title]),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.method(#validateTitle, [title]),
            ),
          )
          as String);

  @override
  String validateContent(String? content) =>
      (super.noSuchMethod(
            Invocation.method(#validateContent, [content]),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.method(#validateContent, [content]),
            ),
          )
          as String);

  @override
  String validateDeadline(_i20.Timestamp? deadline) =>
      (super.noSuchMethod(
            Invocation.method(#validateDeadline, [deadline]),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.method(#validateDeadline, [deadline]),
            ),
          )
          as String);

  @override
  String validatePhoneNumber(String? phoneNumber) =>
      (super.noSuchMethod(
            Invocation.method(#validatePhoneNumber, [phoneNumber]),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.method(#validatePhoneNumber, [phoneNumber]),
            ),
          )
          as String);

  @override
  String validateEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#validateEmail, [email]),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.method(#validateEmail, [email]),
            ),
          )
          as String);

  @override
  void updateTitle(String? newTitle) => super.noSuchMethod(
    Invocation.method(#updateTitle, [newTitle]),
    returnValueForMissingStub: null,
  );

  @override
  void updateContent(String? newContent) => super.noSuchMethod(
    Invocation.method(#updateContent, [newContent]),
    returnValueForMissingStub: null,
  );

  @override
  void updateDeadline(_i20.Timestamp? newDeadline) => super.noSuchMethod(
    Invocation.method(#updateDeadline, [newDeadline]),
    returnValueForMissingStub: null,
  );

  @override
  void updatePhoneNumber(String? newPhoneNumber) => super.noSuchMethod(
    Invocation.method(#updatePhoneNumber, [newPhoneNumber]),
    returnValueForMissingStub: null,
  );

  @override
  void updateEmail(String? newEmail) => super.noSuchMethod(
    Invocation.method(#updateEmail, [newEmail]),
    returnValueForMissingStub: null,
  );

  @override
  void addUser(_i5.User? user) => super.noSuchMethod(
    Invocation.method(#addUser, [user]),
    returnValueForMissingStub: null,
  );

  @override
  void removeUser(_i5.User? user) => super.noSuchMethod(
    Invocation.method(#removeUser, [user]),
    returnValueForMissingStub: null,
  );

  @override
  void addPhoneNumber() => super.noSuchMethod(
    Invocation.method(#addPhoneNumber, []),
    returnValueForMissingStub: null,
  );

  @override
  void removePhoneNumber(String? phoneNumber) => super.noSuchMethod(
    Invocation.method(#removePhoneNumber, [phoneNumber]),
    returnValueForMissingStub: null,
  );

  @override
  void addEmail() => super.noSuchMethod(
    Invocation.method(#addEmail, []),
    returnValueForMissingStub: null,
  );

  @override
  void removeEmail(String? email) => super.noSuchMethod(
    Invocation.method(#removeEmail, [email]),
    returnValueForMissingStub: null,
  );

  @override
  _i13.Future<void> updatePartialUsername(String? partialUsername) =>
      (super.noSuchMethod(
            Invocation.method(#updatePartialUsername, [partialUsername]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  void createTimeCapsule(void Function(_i11.TimeCapsule)? onComplete) =>
      super.noSuchMethod(
        Invocation.method(#createTimeCapsule, [onComplete]),
        returnValueForMissingStub: null,
      );

  @override
  bool updateShouldNotify(
    _i12.CreateTimeCapsuleState? old,
    _i12.CreateTimeCapsuleState? current,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateShouldNotify, [old, current]),
            returnValue: false,
          )
          as bool);

  @override
  _i19.RemoveListener addListener(
    _i21.Listener<_i12.CreateTimeCapsuleState>? listener, {
    bool? fireImmediately = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #addListener,
              [listener],
              {#fireImmediately: fireImmediately},
            ),
            returnValue: () {},
          )
          as _i19.RemoveListener);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
